--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fuyutsuki/AccessorsTrait
build-by-default: true
branches:
- master
projects:
  accessors-trait:
    path: ""
    type: library
    model: virion
...
